<?php
/***************************************************************************
 Extension Name	: New Products
 Extension URL	: http://www.magebees.com/magento-new-products-extension.html
 Copyright		: Copyright (c) 2015 MageBees, http://www.magebees.com
 Support Email	: support@magebees.com 
 ***************************************************************************/
?>
<?php if (($_products = $this->getProductCollection()) && $_products->getSize()): ?>
<div class="newProducts">
	<?php if($this->getDisplayHeading()): ?>
    <div class="title"><h2><?php echo $this->__($this->getHeading()) ?></h2></div>
	<?php endif; ?>

	<?php if(!$this->getIsResponsive()): ?>
		<?php //for default theme(Non Responsive theme) ?>
        <?php echo $this->getPagerHtml() ?>
        <ul class="products-list default">
        <?php $i=0; foreach ($_products->getItems() as $_product): ?>
            <li class="item<?php echo (++$i == count($_products))?' last':''; ?>">
                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="product-image">
                	<img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize( $this->getWidth(),$this->getHeight() ) ?>" width="<?php echo $this->getWidth() ?>" height="<?php echo $this->getHeight() ?>" alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>" />
               	</a>
                <div class="product-shop">
                    <div class="f-fix">
                        <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>)"><?php echo $this->helper('catalog/output')->productAttribute($_product, $_product->getName() , 'name') ?></a></h2>
						<?php if($this->getReview()): ?>
							<?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
						<?php endif; ?>
						<?php if($this->getProductsPrice()): ?>
							<?php echo $this->getPriceHtml($_product, true, '-widget-new-list') ?>
						<?php endif; ?>
						
						<?php if($this->getAddToCart()): ?>
							<?php if ($_product->isSaleable()): ?>
								<p><button type="button" title="<?php echo Mage::helper('core')->htmlEscape($this->__('Add to Cart')) ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button></p>
							<?php else: ?>
								<p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
							<?php endif; ?>
						<?php endif; ?>
						
						<?php if($this->getShortDesc()): ?>
							<div class="desc std">
							<?php
								$short_desc = $this->htmlEscape($_product->getShortDescription());
								echo $this->limit_word($short_desc,$this->getDescLimit());
							?>
							</div>
						<?php endif; ?>
						<?php if($this->getAddToWishlist() || $this->getAddToCompare()): ?>
							<ul class="add-to-links">
								<?php if($this->getAddToWishlist()): ?>
									<?php if ($this->helper('wishlist')->isAllow()) : ?>
										<li><a href="<?php echo $this->getAddToWishlistUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
									<?php endif; ?>
								<?php endif; ?>
								<?php if($this->getAddToCompare()): ?>
										<?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
										<li>
										<?php if($this->getAddToWishlist()): ?>
											<span class="separator">|</span> 
											<?php endif; ?>
											<a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
									<?php endif; ?>
								<?php endif; ?>
							</ul>
						<?php endif; ?>
                    </div>
                </div>
            </li>
        <?php endforeach; ?>
        </ul>
		<script type="text/javascript">decorateList('products-list', 'none-recursive')</script>
		
	<?php else: ?>
		<?php //for responsive theme ?>
		<?php echo $this->getPagerHtml() ?>
        <ul class="products-list rwd">
        <?php $i=0; foreach ($_products->getItems() as $_product): ?>
            <li class="item<?php echo (++$i == count($_products))?' last':''; ?>">
                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="product-image">
                	<img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($this->getWidth(),$this->getHeight()) ?>" alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>" />
                </a>
                <div class="product-shop">
                    <div class="f-fix">
                    	<div class="product-primary">
                            <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>)"><?php echo $this->helper('catalog/output')->productAttribute($_product, $_product->getName() , 'name') ?></a></h2>
                            <?php if($this->getReview()): ?>
                                <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                            <?php endif; ?>
                        </div>
                        <div class="product-secondary">
                        	<?php if($this->getProductsPrice()): ?>
                                <?php echo $this->getPriceHtml($_product, true, '-widget-new-list') ?>
                            <?php endif; ?>
                        </div>
                        <div class="product-secondary">
							<?php if($this->getAddToCart()): ?>
                                <?php if($_product->isSaleable()): ?>
									<button class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')">
											<span><?php echo $this->__('Add to Cart') ?></span>
									</button>
								 <?php elseif($_product->isSaleable()): ?>
									 <button class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')">
											<span><?php echo $this->__('View Details')?></span>
									</button> 
								<?php else: ?>
									<span class="out-of-stock">
										<?php echo $this->__('Out of stock') ?>
									</span>
								<?php endif; ?>
                            <?php endif; ?>
                            <?php if($this->getAddToWishlist() || $this->getAddToCompare()): ?>
                                <ul class="add-to-links">
                                    <?php if($this->getAddToWishlist()): ?>
                                        <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                            <li><a href="<?php echo $this->getAddToWishlistUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                    <?php if($this->getAddToCompare()): ?>
                                        <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                                            <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </ul>
                            <?php endif; ?>
                        </div>
                        <?php if($this->getShortDesc()): ?>
                            <div class="desc std">
                            <?php
                                $short_desc = $this->htmlEscape($_product->getShortDescription());
                                echo $this->limit_word($short_desc,$this->getDescLimit());
                            ?>
                            </div>
                        <?php endif; ?>
					</div>
                </div>
            </li>
        <?php endforeach; ?>
        </ul>
	<?php endif; ?>
</div>
<?php endif; ?>
