<?php
/**
 * Template for checkout page
 *
 * @version 20160203
 */
?>
<?php
    $_isPhp         = $this->isPhpApiPaymentMethod();
    $_controller    = Mage::app()->getFrontController()->getRequest()->getControllerName();
    $_code          = $this->getPaymentCode();
    $currentCode    = Mage::app()->getStore()->getCurrentCurrencyCode();
    $baseCode       = Mage::app()->getStore()->getBaseCurrencyCode();
?>
<?php if($_isPhp): ?>
    <script type="text/javascript">
        var phpCheckoutApi = new checkoutApi(
            '<?php echo $_code ?>',
            '<?php echo $_controller ?>',
            null
        );

        <?php if ($currentCode !== $baseCode):?>
            $$('#checkout-review-table tfoot tr').last().hide();
        <?php endif ?>
    </script>
<?php endif?>
