<?php
/**
 * Template for checkout page
 *
 * @version 20151002
 */
?>
<?php
    $isActive           = $this->isActive();
    $isVisibleCcType    = $this->isVisibleCcType();
    $controller         = Mage::app()->getFrontController()->getRequest()->getControllerName();
?>
<?php if ($isActive):?>
    <ul class="form-list" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
        <?php if($this->isCustomerLogged()): ?>
            <?php $cardList = $this->getCustomerCardList();?>
            <?php if(!empty($cardList)): ?>
                <?php foreach($cardList as $index => $card):?>
                    <li class="checkoutapi-variation">
                        <input class="checkoutapi-saved-card validate-one-required-by-name" type="radio" id="card-<?php echo $index;?>" value="<?php echo $card['value'];?>" name="payment[customer_card]" <?php if(!empty($customerCard) && $customerCard === $card['value']) {echo 'checked=checked';}?>/>
                        <label for="card-<?php echo $index;?>"><?php echo $card['type'] . ' ' . $card['title'];?></label>
                    </li>
                <?php endforeach;?>
                <li class="checkoutapi-variation">
                    <input id="checkoutapi-new-card" class="validate-one-required-by-name" type="radio" name="payment[customer_card]" value="new_card" <?php if(!empty($customerCard) && $customerCard === 'new_card') {echo 'checked=checked';}?>/>
                    <label for="checkoutapi-new-card">Use New Card</label>
                </li>
            <?php endif;?>
        <?php endif;?>
        <li class="checkoutapi-li">
            <label for="<?php echo $this->getMethodCode() ?>_cc_owner"><?php echo $this->__('Name on Card') ?> <span class="required">*</span></label>
            <div class="input-box">
                <input type="text" name="payment[cc_owner]" id="<?php echo $this->getMethodCode() ?>_cc_owner" class="input-text required-entry" title="Name on Card" autocomplete="off" value="">
            </div>
        </li>
        <?php if($isVisibleCcType): ?>
            <li class="checkoutapi-li">
                <label for="<?php echo $this->getMethodCode() ?>_cc_type"><?php echo $this->__('Credit Card Type') ?> <span class="required">*</span></label>
                <div class="input-box">
                    <select id="<?php echo $this->getMethodCode() ?>_cc_type" name="payment[cc_type]" class="required-entry validate-cc-type-select">
                        <option value=""><?php echo $this->__('--Please Select--')?></option>
                        <?php $_ccType = $this->getInfoData('cc_type'); ?>
                        <?php foreach ($this->getCcAvailableTypes() as $_typeCode => $_typeName): ?>
                            <option value="<?php echo $_typeCode ?>"<?php if($_typeCode==$_ccType): ?> selected="selected"<?php endif ?>><?php echo $_typeName ?></option>
                        <?php endforeach ?>
                    </select>
                </div>
            </li>
        <?php endif;?>
        <li class="checkoutapi-li">
            <label for="<?php echo $this->getMethodCode() ?>_cc_number"><?php echo $this->__('Credit Card Number') ?> <span class="required">*</span></label>
            <div class="input-box">
                <?php if($isVisibleCcType): ?>
                    <input type="text" value="<?php echo $this->getInfoData('cc_number')?>" class="input-text required-entry validate-cc-number validate-cc-type" title="Credit Card Number" name="payment[cc_number]" id="<?php echo $this->getMethodCode() ?>_cc_number" pattern="\d*" autocomplete="off">
                <?php else:?>
                    <input type="text" value="<?php echo $this->getInfoData('cc_number')?>" class="input-text required-entry validate-cc-number" title="Credit Card Number" name="payment[cc_number]" id="<?php echo $this->getMethodCode() ?>_cc_number" pattern="\d*" autocomplete="off">
                <?php endif?>
            </div>
        </li>
        <li class="checkoutapi-li">
            <label for="<?php echo $this->getMethodCode() ?>_expiration"><?php echo $this->__('Expiration Date') ?> <span class="required">*</span></label>
            <div class="input-box">
                <select id="<?php echo $this->getMethodCode() ?>_expiration" name="payment[cc_exp_month]"
                        class="month validate-cc-exp required-entry">
                    <?php $_ccExpMonth =  $this->getInfoData('cc_exp_month') ?>
                    <?php foreach ($this->getCcMonths() as $k => $v): ?>
                        <option
                            value="<?php echo $k ? $k : '' ?>"<?php if ($k == $_ccExpMonth): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                    <?php endforeach ?>
                </select>
                <?php $_ccExpYear = $this->getInfoData('cc_exp_year') ?>
                <select id="<?php echo $this->getMethodCode() ?>_expiration_yr" name="payment[cc_exp_year]"
                        class="year required-entry">
                    <?php foreach ($this->getCcYears() as $k => $v): ?>
                        <option
                            value="<?php echo $k ? $k : '' ?>"<?php if ($k == $_ccExpYear): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                    <?php endforeach ?>
                </select>
            </div>
        </li>
        <li class="checkoutapi-li">
            <label for="<?php echo $this->getMethodCode() ?>_cc_cid"><?php echo $this->__('Card Verification Number') ?> <span class="required">*</span></label>
            <div class="input-box">
                <div class="v-fix">
                    <input type="text" name="payment[cc_cid]" id="<?php echo $this->getMethodCode() ?>_cc_cid" class="input-text cvv required-entry validate-cc-cvn" title="Card Verification Number" pattern="\d*" autocomplete="off" value="<?php echo $this->getInfoData('cc_cid')?>">
                </div>
                <a class="cvv-what-is-this" href="#">What is this?</a>
            </div>
        </li>
    </ul>
    <?php if (!empty($cardList)):?>
        <script type="application/javascript">
            hideNewCard();

            $$('.checkoutapi-saved-card').invoke('observe', 'change', hideNewCard);
            $('checkoutapi-new-card').observe('change', showNewCard);

            function hideNewCard() {
                $$('.checkoutapi-li').each(Element.hide);
                $$('.checkoutapi-li input').each(
                    function(Element) {
                        Element.removeClassName('required-entry');
                    }
                );

                $$('.checkoutapi-li select').each(
                    function(Element) {
                        Element.removeClassName('required-entry');
                    }
                );

                $('checkoutapicard_cc_type').removeClassName('validate-cc-type-select');
                $('checkoutapicard_cc_number').removeClassName('validate-cc-type');
                $('checkoutapicard_cc_cid').removeClassName('validate-cc-cvn');
            }

            function showNewCard() {
                $$('.checkoutapi-li').each(Element.show);
                $$('.checkoutapi-li input').each(
                    function(Element) {
                        Element.addClassName('required-entry');
                    }
                );

                $$('.checkoutapi-li select').each(
                    function(Element) {
                        Element.addClassName('required-entry');
                    }
                );

                $('checkoutapicard_cc_type').addClassName('validate-cc-type-select');
                $('checkoutapicard_cc_number').addClassName('validate-cc-type');
                $('checkoutapicard_cc_cid').addClassName('validate-cc-cvn');
            }
        </script>
    <?php endif?>
    <script type="application/javascript">
        var checkoutApiModel = new checkoutApi(
            '<?php echo CheckoutApi_ChargePayment_Helper_Data::CODE_CREDIT_CARD ?>',
            '<?php echo $controller ?>',
            '<?php echo Mage::helper("adminhtml")->getUrl('adminhtml/CheckoutApi_ChargePayment_Api/place') ?>',
            '<?php echo $this->getUrl('*/*/save', array('_secure' => $this->getRequest()->isSecure())) ?>'
        );
    </script>
<?php else:?>
    <ul class="form-list" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
        <li><?php echo $this->__('Selected payment type is not allowed.') ?></li>
    </ul>
<?php endif?>
