<?php
$data = $this->getCollection();
foreach($data as $item){
    $array[] = array($item->getDate(),round($item->getSubtotal()));
}
$jsonData = Mage::helper('core')->jsonEncode($array);
?>

<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
<script type="text/javascript">
    google.charts.load('current', {'packages':['table']});
    google.charts.setOnLoadCallback(drawTable);

    function drawTable() {
        var data = new google.visualization.DataTable();
        data.addColumn('string', 'data');
        data.addColumn('number', 'qty ordered');
        data.addRows(<?php echo $jsonData;?>);

        var table = new google.visualization.Table(document.getElementById('table_div'));

        table.draw(data, {showRowNumber: false, width: '100%', height: '100%'});
    }
</script>

<div id="table_div" style="margin: 20px 0;width: 500px;"></div>

