<div class="banners row">
	<div class="col-sm-8">
		<a href="{{store url=''}}collection.html">
			<img src="{{skin url='images/banner-1.jpg'}}" alt="" />
			<span class="s-desc">
				<h1>Shoes</h1>
				<h2>Up to 70% off</h2>
				<span>Shop now!</span>
			</span>
		</a>
		<div class="row">
			<div class="col-sm-6">
				<a href="{{store url=''}}outerwear.html">
					<img src="{{skin url='images/banner-2.jpg'}}" alt="" />
					<span class="s-desc">
						<h1>Designer<br /> collection</h1>
						<h2>Up to 30% off</h2>
						<span>Shop now!</span>
					</span>
				</a>
			</div>
			<div class="col-sm-6">
				<a href="{{store url=''}}women.html">
					<img src="{{skin url='images/banner-3.jpg'}}" alt="" />
					<span class="s-desc">
						<h1>Handbags</h1>
						<h2>Up to 30% off</h2>
						<span>Shop now!</span>
					</span>
				</a>
			</div>
		</div>
	</div>
	<div class="col-sm-4">
		<a href="{{store url=''}}men.html">
			<img src="{{skin url='images/banner-4.jpg'}}" alt="" />
			<span class="s-desc">
				<h1>Men's <br />clothing</h1>
				<h2>Up to 70% off</h2>
				<span>Shop now!</span>
			</span>
		</a>
	</div>
</div>