<?php
/**
 * Adyen Payment Module
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category	Adyen
 * @package	Adyen_Payment
 * @copyright	Copyright (c) 2011 Adyen (http://www.adyen.com)
 * @license	http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
/**
 * @category   Payment Gateway
 * @package    Adyen_Payment
 * @author     Adyen
 * @property   Adyen B.V
 * @copyright  Copyright (c) 2014 Adyen BV (http://www.adyen.com)
 */
$_code=$this->getMethodCode();
?>

    <ul id="payment_form_<?php echo $_code ?>" style="display:none">
        <li>
            <div class="input-box">
                <label for="<?php echo $_code ?>_social_security_number"><?php echo $this->__('Social Security Number') ?> <span class="required">*</span></label><br />
                <input type="text" title="<?php echo $this->__('Social Security Number') ?>" class="validate-ipayment-boleto-social-security-number required-entry input-text" id="<?php echo $_code ?>_social_security_number" name="payment[social_security_number]" value="" />
            </div>
        </li>
        
        <?php if(count($this->getBoletoAvailableTypes()) == 1) {?>
        	<input id="<?php echo $_code ?>_boleto_type" type="hidden" name="payment[boleto_type]" value="<?php echo current($this->getBoletoAvailableTypes()); ?>" />
        <?php } else {?>
        <li>
        	<div class="input-box">
	        	<label for="<?php echo $_code ?>_boleto_type"><?php echo Mage::helper('payment')->__('Boleto Card Type') ?> <span class="required">*</span></label><br/>
                <select id="<?php echo $_code ?>_boleto_type" name="payment[boleto_type]" title="<?php echo $this->__('Boleto Card Type') ?>" class="required-entry">
	                <option value=""><?php echo $this->__('--Please Select--') ?></option>
	            <?php $_boletoType = $this->getInfoData('boleto_type') ?>
	            <?php foreach ($this->getBoletoAvailableTypes() as $_typeCode => $_typeName): ?>
	                <option value="<?php echo $_typeCode ?>"<?php if($_typeCode==$_boletoType): ?> selected="selected"<?php endif ?>><?php echo $_typeName ?></option>
	            <?php endforeach ?>
	            </select>
	        </div>
	    </li>
	    <?php } ?>

        <li>
            <div class="input-box">
                <label for="<?php echo $_code ?>_firstname"><?php echo $this->__('Firstname') ?> <span class="required">*</span></label><br />
                <input 
                	type="text" id="<?php echo $_code ?>?>_firstname" name="payment[firstname]" 
                	title="<?php echo $this->__('Firstname') ?>" 
                	class="validate-ipayment-boleto-firstname required-entry input-text" 
                	value="" />
            </div>
        </li>
         <li>
            <div class="input-box">
                <label for="<?php echo $_code ?>_lastname"><?php echo $this->__('Lastname') ?> <span class="required">*</span></label><br />
                <input 
	                type="text" id="<?php echo $_code ?>_lastname" name="payment[lastname]" 
	                title="<?php echo $this->__('Lastname') ?>" 
	                class="validate-ipayment-boleto-lastname required-entry input-text" 
	                value="" />
            </div>
        </li>
    </ul>

<div>
</div>

