<?php
/**
 * Adyen Payment Module
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category	Adyen
 * @package	Adyen_Payment
 * @copyright	Copyright (c) 2011 Adyen (http://www.adyen.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
/**
 * @category   Payment Gateway
 * @package    Adyen_Payment
 * @author     Adyen
 * @property   Adyen B.V
 * @copyright  Copyright (c) 2014 Adyen BV (http://www.adyen.com)
 */
/** @var $this Adyen_Payment_Block_Form_Oneclick */
?>
<?php $_code=$this->getMethodCode() ?>
<ul id="payment_form_<?php echo $_code ?>" style="display:none;">
    <li>
        <?php
        $recurringDetails = $this->getRecurringDetails();
        if(isset($recurringDetails["variant"])):
        ?>

        <?php if(isset($recurringDetails["card_number"]) && isset($recurringDetails["card_expiryMonth"]) && isset($recurringDetails["card_expiryYear"]) ): ?>
            <div class="columns three a">
                <label><?php echo $this->__('Credit Card Number') ?></label>
                <span>****</span> <?php echo $recurringDetails["card_number"]; ?>
            </div>

            <div class="columns three b">
                <label><?php echo $this->__('Expiration Date') ?><a href="#" id="update-expiration-date-<?php echo $_code; ?>" class="update-expiration-date"><?php echo $this->__('(update)') ?></a></label>

                <div id="static-card-expiry-<?php echo $_code; ?>" class="static-card-expiry">
                    <?php echo $recurringDetails["card_expiryMonth"] . " /" . $recurringDetails["card_expiryYear"]; ?>
                </div>
                <div id="changable-card-expiry-<?php echo $_code; ?>" class="changable-card-expiry" style="display:none;">
                    <select id="<?php echo $_code ?>_expiration_<?php echo $_code; ?>" <?php echo (!$this->isCseEnabled() ? "name=\"payment[oneclick_exp_month]\"" : "data-encrypted-name-oneclick-" . $_code . "=expiryMonth"); ?> class="month validate-oneclick-exp required-entry">
                        <?php foreach ($this->getCcMonths() as $k=>$v): ?>
                            <option value="<?php echo $k?$k:'' ?>"<?php if($k==$recurringDetails["card_expiryMonth"]): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                        <?php endforeach ?>
                    </select>

                    <select id="<?php echo $_code ?>_expiration_yr_<?php echo $_code; ?>" <?php echo (!$this->isCseEnabled() ? "name=\"payment[oneclick_exp_year]\"" : "data-encrypted-name-oneclick-" . $_code . "=expiryYear"); ?> class="year required-entry">
                        <?php foreach ($this->getCcYears() as $k=>$v): ?>
                            <option value="<?php echo $k?$k:'' ?>"<?php if($k==$recurringDetails["card_expiryYear"]): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                        <?php endforeach ?>
                    </select>
                </div>
            </div>

         <?php if( $this->showCvc()):?>
            <div class="columns three c">
                <label><?php echo $this->__('Card Verification Number') ?></label>
                <?php if($this->hasVerification()): ?>
                    <div class="cvc_block" id="cvc_block_<?php echo $_code;?>">
                        <input type="text" pattern="[0-9]{3,}" title="<?php echo $this->__('Card Verification Number') ?>" class="input-text cvv required-entry" id="<?php echo $_code ?>_cc_cid" <?php echo (!$this->isCseEnabled() ? "name=\"payment[oneclick_cid_".$_code."]\"" : "data-encrypted-name-oneclick-" . $_code ."=cvc"); ?> value="" />
                        <a href="#" class="cvv-what-is-this"><?php echo $this->__('What is this?') ?></a>
                    </div>
                <?php endif; ?>
            </div>
        <?php endif; ?>

        <?php if($this->hasInstallments()): ?>
            <div id="adyen_oneclick_installment_<?php echo $_code;?>" class="adyen-oneclick-installments">
                <label for="<?php echo $_code ?>_installment_<?php echo $_code; ?>" class="required"><em>*</em><?php echo $this->__('Installments') ?></label>
                <div class="input-box">
                    <div class="v-fix">
                        <select id="<?php echo $_code ?>_installment" name="payment[installment]" class="adyen-installment number required-entry">
                            <?php foreach ($this->getInstallments() as $k=>$v): ?>
                                <option value="<?php echo $k?$k:'' ?>"><?php echo $v ?></option>
                            <?php endforeach ?>
                        </select>
                    </div>
                </div>
            </div>
        <?php endif;?>

        <?php if ($this->isCseEnabled()): ?>
        <input type="hidden" id="<?php echo $_code ?>_encrypted_form_expiry_generationtime" value="<?php echo date("c"); ?>" data-encrypted-name-oneclick-<?php echo $_code ?>="generationtime" />
            <script type="text/javascript">

                // update-expiration-date action
                $$('.update-expiration-date').each(function(element) {
                    element.observe('click', updateExpirationDate);
                });
                // show the expiration month and year
                function updateExpirationDate(event) {
                    // hide the link
                    this.hide();
                    // show expiration month and year
                    var id = this.id.replace("update-expiration-date-", "");
                    var changableId = "changable-card-expiry-" + id;
                    var staticId = "static-card-expiry-" + id;
                    // show changeble card expiry
                    $(staticId).hide();
                    $(changableId).show();
                    event.preventDefault();
                }

                var cse_key_oneclick = <?php echo json_encode($this->getCsePublicKey()); ?>;
                var cse_options_oneclick = {
                    name:  'payment[encrypted_data_oneclick]',
                    force: true
                };

                var cseUpdateOneClick = function() {

                    try {
                        if (order.paymentMethod && order.paymentMethod == '<?php echo $_code ?>') {
                            var elementOneClick = $('payment_form_<?php echo $_code ?>');
                            var cse_form_oneclick =  elementOneClick.match('form') ? elementOneClick : elementOneClick.up('form');

                            // add this field to option
                            cse_options_oneclick.fieldNameAttribute = "data-encrypted-name-oneclick-<?php echo $_code ?>";

                            // do not validate because number does not exists for oneclick
                            cse_options_oneclick.enableValidations = false;

                            var cseFormOneClick = adyen.encrypt.createEncryptedForm(cse_form_oneclick, cse_key_oneclick, cse_options_oneclick);
                            // encrypt data directly because submit button is not always on the page
                            cseFormOneClick.createEncryptedField(cseFormOneClick.encrypt());
                        }
                    } catch (e) {
                        if (typeof console == "object") {
                            console.error(e);
                        } else {
                            alert("Warning: Adyen Client Side Encryption cannot succeed.");
                        }
                    }

                };

                var cseInitOneClick = function() {
                    if (typeof adyen === 'undefined') {
                        var script = document.createElement("script");
                        script.type = "text/javascript";
                        script.src = "<?php echo $this->getJsUrl('adyen/payment/adyen.encrypt_0_1_18.js'); ?>";
                        document.body.appendChild(script);
                    }

                    // if the browser does not support forach method implement it
                    if (!Array.prototype.forEach) {
                        Array.prototype.forEach = function(fn, scope) {
                            for(var i = 0, len = this.length; i < len; ++i) {
                                fn.call(scope, this[i], i, this);
                            }
                        }
                    }

                    var fields = $$('#payment_form_<?php echo $_code ?> input, #payment_form_<?php echo $_code ?> textarea, #payment_form_<?php echo $_code ?> select');
                    fields.forEach(function(field) {
                        field.observe('change', cseUpdateOneClick);
                    });
                };

                cseInitOneClick();
            </script>
        <?php endif;?>

        <?php elseif($recurringDetails["variant"] == "elv"): ?>
            <div class="columns three a">
                <label><?php echo $this->__('Account holder name') ?></label>
                <span><?php echo $recurringDetails["elv_accountHolderName"]; ?></span>
            </div>
            <div class="columns three b">
                <label><?php echo $this->__('Account Number') ?></label>
                <span><?php echo $recurringDetails["elv_bankAccountNumber"]; ?></span>
            </div>
            <div class="columns three c">
                <label><?php echo $this->__('Bank Name') ?></label>
                <span><?php echo $recurringDetails["elv_bankName"]; ?></span>
            </div>
        <?php elseif($recurringDetails["variant"] == "openinvoice"): ?>
            <div class="columns three a">
                <label><?php echo $this->__('Bank account holder name') ?></label>
                <span><?php echo $recurringDetails["bank_ownerName"]; ?></span>
            </div>
            <div class="columns three b">
                <label><?php echo $this->__('Bank Account Number') ?></label>
                <span><?php echo $recurringDetails["bank_bankAccountNumber"]; ?></span>
            </div>
            <div class="columns three c">
                <label><?php echo $this->__('Country') ?></label>
                <span><?php echo $recurringDetails["bank_countryCode"]; ?></span>
            </div>
        <?php elseif($recurringDetails["variant"] == "sepadirectdebit" || $recurringDetails["variant"] == "ideal" ): ?>
            <div class="columns three a">
                <label><?php echo $this->__('Bank account holder name') ?></label>
                <span><?php echo $recurringDetails["bank_ownerName"]; ?></span>
            </div>
            <div class="columns three b">
                <label><?php echo $this->__('IBAN') ?></label>
                <span><?php echo $recurringDetails["bank_iban"]; ?></span>
            </div>
            <div class="columns three c">
                <label><?php echo $this->__('Country') ?></label>
                <span><?php echo $recurringDetails["bank_countryCode"]; ?></span>
            </div>
        <?php endif;?>
        <?php endif;?>
    </li>
</ul>
