<?php
/**
 * Adyen Payment Module
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category    Adyen
 * @package    Adyen_Payment
 * @copyright    Copyright (c) 2011 Adyen (http://www.adyen.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
/**
 * @category   Payment Gateway
 * @package    Adyen_Payment
 * @author     Adyen
 * @property   Adyen B.V
 * @copyright  Copyright (c) 2014 Adyen BV (http://www.adyen.com)
 */
?>
<?php $disabled = $this->getMethod()->getHppOptionsDisabled(); ?>
<?php if ($disabled): ?>
    <?php echo $this->htmlEscape($this->getMethod()->getTitle()) ?><br/>
<?php endif; ?>

<?php if ($_info = $this->getInfo()): ?>
    <?php $paymentMethod = $_info->getCcType() ?>
    <?php if (!empty($paymentMethod)): ?>
        <?php echo $this->__('Payment Method: %s', $this->htmlEscape($_info->getAdditionalInformation('hpp_type_label'))) ?>
        <br/>
    <?php endif; ?>
    <?php if (strpos($paymentMethod, "ideal") !== false): ?>
        <?php $bankData = $_info->getAdditionalInformation("hpp_issuer_id"); ?>
        <?php if (!empty($bankData)) : ?>
            <?php
            $label = $_info->getAdditionalInformation('hpp_type_bank_label');
            ?>
            <?php echo $this->__('Bank: %s', $this->htmlEscape($label)) ?><br/>
        <?php endif; ?>
    <?php endif; ?>
<?php endif; ?>