<?php
/**
 * Payssion Payment Module
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category	Payssion
 * @package	Payssion_Payment
 * @copyright	Copyright (c) 2015 Payssion (http://www.payssion.com)
 * @license	http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
/**
 * @category   Payment Gateway
 * @package    Payssion_Payment
 * @author     Payssion
 * @property   Payssion Limited
 * @copyright  Copyright (c) 2015 Payssion Limited (http://www.payssion.com)
 */
?>

<img style="margin-right: 6px;" src="<?php echo $this->getPaymentMethodIcon(); ?>" height="43" alt="<?php echo $this->getPaymentMethodLabel() ?>" border="0"/>
<span><?php echo $this->getPaymentMethodLabel() . ' (via Payssion)'; ?></span>

