<?php 
if (Mage::getStoreConfig('twitter/twitter_timeline/active', Mage::app()->getStore())):	

	$tm_twitter_settings = array(
		'widget_id' 		=> Mage::getStoreConfig('twitter/twitter_timeline/widget_id', Mage::app()->getStore()),
		'account_name' 		=> Mage::getStoreConfig('twitter/twitter_timeline/account_name', Mage::app()->getStore()),
		'color_scheme' 		=> Mage::getStoreConfig('twitter/twitter_timeline/color_scheme', Mage::app()->getStore()),
		'link_color' 		=> Mage::getStoreConfig('twitter/twitter_timeline/link_color', Mage::app()->getStore()),
		'border_color' 		=> Mage::getStoreConfig('twitter/twitter_timeline/border_color', Mage::app()->getStore()),
		'tweet_limit' 		=> Mage::getStoreConfig('twitter/twitter_timeline/tweet_limit', Mage::app()->getStore()),
		'data_height' 		=> Mage::getStoreConfig('twitter/twitter_timeline/data_height', Mage::app()->getStore()),
		'data_width' 		=> Mage::getStoreConfig('twitter/twitter_timeline/data_width', Mage::app()->getStore()),
		'chrome_layout' 	=> Mage::getStoreConfig('twitter/twitter_timeline/chrome_layout', Mage::app()->getStore()),
		);
	
	$chrome_layouts = str_replace(',', ' ', $tm_twitter_settings['chrome_layout']);	?>

	<div class="block block-twitter_timeline">
	    <div>
	        <h4><?php echo $this->__('Twitter Timeline') ?></h4>
	    </div>
		<div>
			<a class="twitter-timeline"  href="https://twitter.com/<?php echo $tm_twitter_settings['account_name']; ?>" 
				data-widget-id="<?php echo $tm_twitter_settings['widget_id']; ?>" 
				data-theme="<?php echo $tm_twitter_settings['color_scheme']; ?>" 
				data-link-color="<?php echo $tm_twitter_settings['link_color']; ?>" 
				width="<?php echo $tm_twitter_settings['data_width']; ?>" 
				height="<?php echo $tm_twitter_settings['data_height']; ?>"
				data-border-color="<?php echo $tm_twitter_settings['border_color']; ?>"
				data-tweet-limit="<?php echo $tm_twitter_settings['tweet_limit']; ?>" 
				data-chrome="<?php echo $chrome_layouts; ?>" 
				><?php echo $this->__('Tweets by') ?> @<?php echo $tm_twitter_settings['account_name']; ?></a>

            <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
	    </div>
	</div>
<?php endif; ?>