<?php
/**
 * Adyen Payment Module
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category	Adyen
 * @package	Adyen_Payment
 * @copyright	Copyright (c) 2011 Adyen (http://www.adyen.com)
 * @license	http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
/**
 * @category   Payment Gateway
 * @package    Adyen_Payment
 * @author     Adyen
 * @property   Adyen B.V
 * @copyright  Copyright (c) 2014 Adyen BV (http://www.adyen.com)
 */
?>

<?php if ($this->displayBoth()):?>
    <tr>
        <td style="<?php echo $this->getStyle() ?>" class="a-right" colspan="<?php echo $this->getColspan(); ?>">
            <?php echo $this->getExcludeTaxLabel() ?>
        </td>
        <td style="<?php echo $this->getStyle() ?>" class="a-right">
            <?php echo $this->formatPrice($this->getPaymentFeeExcludeTax()) ?>
        </td>
    </tr>
    <tr>
        <td style="<?php echo $this->getStyle() ?>" class="a-right" colspan="<?php echo $this->getColspan(); ?>">
            <?php echo $this->getIncludeTaxLabel() ?>
        </td>
        <td style="<?php echo $this->getStyle() ?>" class="a-right">
            <?php echo $this->formatPrice($this->getPaymentFeeIncludeTax()) ?>
        </td>
    </tr>
<?php elseif($this->displayIncludeTax()) : ?>
    <tr>
        <td style="<?php echo $this->getStyle() ?>" class="a-right" colspan="<?php echo $this->getColspan(); ?>">
            <?php echo $this->getTotal()->getTitle() ?>
        </td>
        <td style="<?php echo $this->getStyle() ?>" class="a-right">
            <?php echo $this->formatPrice($this->getPaymentFeeIncludeTax()) ?>
        </td>
    </tr>
<?php else:?>
    <tr>
        <td style="<?php echo $this->getStyle() ?>" class="a-right" colspan="<?php echo $this->getColspan(); ?>">
            <?php echo $this->escapeHtml($this->getTotal()->getTitle()) ?>
        </td>
        <td style="<?php echo $this->getStyle() ?>" class="a-right">
            <?php echo $this->formatPrice($this->getPaymentFeeExcludeTax()) ?>
        </td>
    </tr>
<?php endif;?>
