<?php
/***************************************************************************
 Extension Name	: New Products
 Extension URL	: http://www.magebees.com/magento-new-products-extension.html
 Copyright		: Copyright (c) 2015 MageBees, http://www.magebees.com
 Support Email	: support@magebees.com 
 ***************************************************************************/
?>
<style>
	.product-param label { padding-right: 10px; }
	.product-param .label { color: black; font-weight: bold; }
	.product-param .label:hover { color: blue; font-weight: bold; }
	.product-param .element { display: none; }
	.product-param input, .product-param select { min-width: 350px; width: auto !important; }
	.product-param-edit .label { display: none; }
	.product-param-edit .element { display: inline; }
	.product-chooser { border: 1px solid #CCC; display: none; margin: 10px 0; padding: 5px; }
	.display-default {display: inline;}
</style>
<?php $store_id = Mage::app()->getRequest()->getParam('store',0);?>
<input type="hidden" name="store_id" id="store_id" value="<?php echo $store_id ?>">
<div class="entry-edit">
	<div class="entry-edit-head">
		<h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('newproducts')->__('Manually Products') ?></h4>
		
	</div>
	<fieldset id="product_fieldset">
		<ul>
			<li>
				<span class="product-param">
					<label for="product_sku"><?php echo Mage::helper('newproducts')->__('Select New Product SKUs') ?></label>
						<a class="label" href="javascript:void(0)"><?php if($this->getSkusString()) { echo $this->getSkusString(); } else { echo Mage::helper('newproducts')->__('Click Here To Add Products'); } ?></a>
					<span class="element">
						<input id="product_sku" class="input-text element-value-changer" type="text" value="<?php echo $this->getSkusString() ?>" name="product_sku">
						<a class="product-chooser-trigger" href="javascript:void(0)">
							<img id="chooser" src="<?php echo Mage::getDesign()->getSkinUrl('images/rule_chooser_trigger.gif') ?>" alt="" class="v-middle product-chooser-trigger" title="<?php echo Mage::helper('newproducts')->__('Open Chooser') ?>" />
						</a>
					</span>
				</span>
				<div id="product-grid" class="product-chooser" url="<?php echo Mage::getUrl('adminhtml/widget/chooser/attribute/sku/form/rule_conditions_fieldset', array('_secure' => Mage::app()->getStore()->isAdminUrlSecure(),'store'=>$store_id)); ?>">
				</div>
			</li>
		</ul>
	</fieldset>
</div>

<script type="text/javascript">
	var rule_conditions_fieldset = new VarienRulesForm('product_fieldset', '<?php echo Mage::getUrl('/admin/promo_catalog/newConditionHtml/form/rule_conditions_fieldset/', array('_secure' => Mage::app()->getStore()->isAdminUrlSecure())) ?>');
</script>