<?php
$data = $this->getCollection();
foreach($data as $item){
    $array[] = array($item->getDate(),(int)$item->getProcessing(),(int)$item->getComplete(),(int)$item->getPending(),(int)$item->getPendingPayment(),(int)$item->getCanceled(),(int)$item->getClosed(),(int)$item->getProcessing()+(int)$item->getComplete());
}
$jsonData = Mage::helper('core')->jsonEncode($array);
?>

<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
<script type="text/javascript">
    google.charts.load('current', {'packages':['table']});
    google.charts.setOnLoadCallback(drawTable);

    function drawTable() {
        var data = new google.visualization.DataTable();
        data.addColumn('string', 'data');
        data.addColumn('number', 'Processing');
        data.addColumn('number', 'completed');
        data.addColumn('number', 'pending');
        data.addColumn('number', 'pending_payment');
        data.addColumn('number', 'cancel');
        data.addColumn('number', 'closed');
        data.addColumn('number','Total')
        data.addRows(<?php echo $jsonData;?>);

        var table = new google.visualization.Table(document.getElementById('table_div'));

        table.draw(data, {showRowNumber: false, width: '100%', height: '100%'});
    }
</script>


<div id="table_div" style="margin-top: 20px;"></div>


