<?php
/**
 * Template for checkout page
 *
 * @version 20160202
 */
?>
<?php $isActive = $this->isActive();?>
<?php if ($isActive):?>
    <?php $tokenResult = $this->getPaymentTokenResult(); ?>
    <?php if (!empty($tokenResult)): ?>
        <ul class="form-list" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
            <?php if ($tokenResult['success']):?>
                <li id="payment_form_<?php echo $this->getMethodCode() ?>_block"><img src="<?php echo $this->getSkinUrl('images/checkout.jpg');?>" /></li>
                <li>
                    <script type="text/javascript">
                        window.checkoutIntegrationHostedConfig = {
                            debugMode: 'false',
                            renderMode: <?php echo $this->getRenderMode() ?>,
                            publicKey: '<?php echo $this->getPublicKey();?>',
                            paymentToken: '<?php echo $tokenResult['token'];?>',
                            customerEmail: '<?php echo $tokenResult['customerEmail'];?>',
                            customerName: '<?php echo $tokenResult['customerName'];?>',
                            value: '<?php echo $tokenResult['value'];?>',
                            currency: '<?php echo $tokenResult['currency'];?>',
                            //widgetContainerSelector: '#payment_form_<?php //echo $this->getMethodCode() ?>_block',
                            paymentMode: '<?php echo $this->getPaymentMode();?>',
                            widgetColor: '#333',
                            cardFormMode: '<?php echo $this->getCardFormMode();?>'
                        };

                        window.checkoutHostedIntegrationIsReady = window.checkoutHostedIntegrationIsReady || false;
                        if (!window.checkoutHostedIntegrationIsReady) {
                            window.CKOConfig = {
                                namespace: 'CKOAPIHOSTED',
                                ready: function () {

                                    if (window.checkoutHostedIntegrationIsReady) {
                                        return false;
                                    }

                                    if (typeof CKOAPIHOSTED == 'undefined') {
                                        return false;
                                    }

                                    CKOAPIHOSTED.render(window.checkoutIntegrationHostedConfig);

                                    window.checkoutHostedIntegrationIsReady = true;
                                }
                            };

                            var script = document.createElement('script');
                            script.type = "text/javascript";
                            script.src = '<?php echo $this->getHostedJsPath();?>';
                            script.async = true;
                            document.head.appendChild(script);
                        } else {
                            CKOAPIHOSTED.render(window.checkoutIntegrationHostedConfig);
                        }
                    </script>
                </li>
            <?php else:?>
                <li><?php echo $this->__($tokenResult['message']) ?></li>
            <?php endif?>
        </ul>
    <?php endif;?>
<?php else :?>
    <ul class="form-list" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
        <li><?php echo $this->__('Selected Payment Type is not allowed.') ?></li>
    </ul>
<?php endif?>
