<?php
/**
 * Adyen Payment Module
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category	Adyen
 * @package	Adyen_Payment
 * @copyright	Copyright (c) 2011 Adyen (http://www.adyen.com)
 * @license	http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
/**
 * @category   Payment Gateway
 * @package    Adyen_Payment
 * @author     Adyen
 * @property   Adyen B.V
 * @copyright  Copyright (c) 2014 Adyen BV (http://www.adyen.com)
 */
$_code = $this->getMethodCode();
/** @var $this Adyen_Payment_Block_Form_Sepa */
?>


<fieldset class="form-list">

    <script type="text/javascript">
        // check if apple pay is available for shopper
        if(window.ApplePaySession) {
//            var promise = ApplePaySession.canMakePaymentsWithActiveCard("<?php //echo $this->getMerchantIdentifier(); ?>//");
//            promise.then(function (canMakePayments) {
//                if (canMakePayments) {
                    $('AdyenApplePayError').hide();
                    $('AdyenAllowApplePay').setValue("1");
//                }
//            });
        }
    </script>

    <ul id="payment_form_<?php echo $_code ?>" style="display:none">
        <li id="AdyenApplePayError">
            <?php echo $this->__('Your browser does not support ApplePay or you don\'t have any active cards in your wallet.') ?>
            <input type="hidden" id="AdyenAllowApplePay" name="payment[allow_apple_pay]" value="0"/>
        </li>
    </ul>
</fieldset>

