<?php
/**
 * Adyen Payment Module
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category    Adyen
 * @package    Adyen_Payment
 * @copyright    Copyright (c) 2011 Adyen (http://www.adyen.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
/**
 * @category   Payment Gateway
 * @package    Adyen_Payment
 * @author     Adyen
 * @property   Adyen B.V
 * @copyright  Copyright (c) 2014 Adyen BV (http://www.adyen.com)
 */
?>
<?php $_code = $this->getMethodCode() ?>
<?php $disabled = $this->getHppOptionsDisabled(); ?>
<?php if ($disabled): ?>
    <fieldset class="form-list">
        <ul id="payment_form_<?php echo $_code ?>" style="display:none">
            <li>
                <?php echo $this->__('You will be redirected to Adyen website when you place an order.') ?>
            </li>
        </ul>
    </fieldset>
<?php endif; ?>
<?php if (count($this->getIssuers()) > 0): ?>
    <ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none">
        <li>
            <label for="payment[adyen_issuer_type]">
                <?php echo $this->__('Choose Your Bank') ?>
            </label>
            <select class="adyen_select_issuer validate-select" name="payment[adyen_issuer_type]">
                <option value=""><?php echo $this->__('Choose Your Bank'); ?></option>
                <?php foreach ($this->getIssuers() as $_issuerId => $_issuerData): ?>
                    <option value="<?php echo $_issuerId ?>"
                            <?php if (isset($_issuerData['selected'])): ?>selected<?php endif; ?>>
                        <?php echo $_issuerData['label']; ?>
                    </option>
                <?php endforeach; ?>
            </select>
        </li>
    </ul>
<?php endif; ?>
<?php
