<?php
/**
 * Adyen Payment Module
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category	Adyen
 * @package	Adyen_Payment
 * @copyright	Copyright (c) 2011 Adyen (http://www.adyen.com)
 * @license	http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
/**
 * @category   Payment Gateway
 * @package    Adyen_Payment
 * @author     Adyen
 * @property   Adyen B.V
 * @copyright  Copyright (c) 2014 Adyen BV (http://www.adyen.com)
 */
?>
<?php $_code = $this->getMethodCode() ?>

<fieldset class="form-list">
    <ul id="payment_form_<?php echo $_code ?>" style="display:none">
        <li>
            <?php echo $this->__('You will be redirected to Adyen app when you place an order.') ?> 
        </li>
        <?php if($this->showRememberThisCheckoutbox()): ?>
            <li id="adyen-remember-these-details" class="adyen_payment_input_fields">
                <div class="input-box">
                    <div class="v-fix">
                        <input type="checkbox" name="payment[store_cc]" id="<?php echo $_code ?>_store_cc" value="1" checked />
                        <label for="<?php echo $_code ?>_store_cc" class="required"><em>*</em><?php echo $this->__('Remember these details') ?></label>
                    </div>
                </div>
            </li>
            <script type="text/javascript">
                // don't show save cc for quest checkout. Only possible to detect with javascript
                if ($('login:guest') && $('login:guest').checked) {
                    $('adyen-remember-these-details').hide();
                }
            </script>
        <?php endif; ?>
    </ul>
</fieldset>