<?php

/**
 * Adyen Payment Module
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category	Adyen
 * @package	Adyen_Payment
 * @copyright	Copyright (c) 2011 Adyen (http://www.adyen.com)
 * @license	http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
/**
 * @category   Payment Gateway
 * @package    Adyen_Payment
 * @author     Adyen
 * @property   Adyen B.V
 * @copyright  Copyright (c) 2014 Adyen BV (http://www.adyen.com)
 */
?>
<?php if($this->hasEnableScanner()): ?>
<div id="adyenCustomScanWrapper">
    <form id="addToCartBarCode" method='post' action="<?php echo  $this->getUrl("adyen/updateCart/index", array('_secure'=>true)); ?>">

        <h3>Barcode scanner</h3>

        <div id="scan">
            <input type="text" class="input-text" name="code" id="inpscan" value="" size="60"  placeholder="Scan barcode with scanner" autocomplete="off" autofocus/>
        </div>

        <?php if($this->hasAutoSubmitScanner()): ?>
            <button style="visibility: hidden;" id="SubmitScan" type="submit" title="Submit" class="button btn-proceed-checkout btn-checkout">
            </button>
        <?php endif; ?>


        <div id="customscan" style="display:none;">
            <input type="text" class="input-text" name="customcode" id="inpcustomscan" value="" size="60"  placeholder="Fil in custom barcode">
            <button id="SubmitCustomScan" type="submit" title="Submit" class="button btn-proceed-checkout btn-checkout">
                <span><span>Add</span></span>
            </button>
        </div>

        <br />
        <button id="StopCustomScan" type="button" title="Custom barcode" class="button btn-proceed-checkout btn-checkout">
            <span><span>Custom barcode</span></span>
        </button>

        <button id="StartScan" style="display:none; margin:0;" type="button" title="Start Auto Scanning" class="button btn-proceed-checkout btn-checkout">
            <span><span>Start Auto Scanning</span></span>
        </button>

    </form>


    <script type="text/javascript">


        var intervalId;
        var scanInProgress = false;

        // show autostart button for IOS because they block the onload focus event
        var iOS = ( navigator.userAgent.match(/(iPad|iPhone|iPod)/g) ? true : false );
        if(iOS) {
            // show auto startscan buttton
            $('StartScan').show();
        }

        $('inpscan').observe('focus', function(e){
            $('StartScan').hide();
            <?php if(!$this->hasAutoSubmitScanner()): ?>
                intervalId = setInterval('scan()', 250);
            <?php endif; ?>
        });

        $('inpscan').observe('blur', function(e){

            clearInterval(intervalId);
            $('StartScan').show();
        });

        $('StartScan').observe('click', function(e){

            $('scan').show();
            $('customscan').hide();

            $('StopCustomScan').show();

            $('inpscan').focus();
            intervalId = setInterval('scan()', 250);
            $('StartScan').hide();

        });

        $('StopCustomScan').observe('click', function(e){
            $('scan').hide();
            $('customscan').show();
            $('inpcustomscan').focus();
            $('StopCustomScan').hide();
            $('StartScan').show();

        });

        $('SubmitCustomScan').observe('click', function(e){
            var value =  $('inpcustomscan').value;;
            ajaxCall(value);
            $('inpcustomscan').value = "";
            $('inpcustomscan').focus();
            e.preventDefault();
        });

        function adyenposLoaded() {
            adyenpos.on("barcodeReceived", function(barcode) {
                ajaxCall(barcode);
            });
        }

        <?php if($this->hasAutoSubmitScanner()): ?>
            $('SubmitScan').observe('click', function(e){
                var value =  $('inpscan').value;;
                ajaxCall(value);
                $('inpscan').value = "";
                $('inpscan').focus();
                e.preventDefault();
            });
        <?php endif; ?>



        // check if scan is done with scanning
        function checkValueInput(value) {

            var currentValue = $('inpscan').value;

            if(value == currentValue) {
                // DO ajax call
                ajaxCall(value);
                $('inpscan').value = "";
                this.scanInProgress = false;
                return;
            }

            // call same function after certain period of time
            var test = setTimeout("checkValueInput($('inpscan').value)", 100);
        }


        function scan() {

            if(this.scanInProgress === false) {

                // get value
                var value = $('inpscan').value;
                if(value) {
                    this.scanInProgress = true;

                    // extra check for full input from scanner
                    setTimeout("checkValueInput($('inpscan').value)", 250);
                }
            }
        }

        function ajaxCall(code) {

            var form = document.getElementById("addToCartBarCode");
            new Ajax.Request(form.action, {
                parameters: {code: code, isAjax: 1, method: 'POST'},
                onSuccess: function(transport) {

                    var response = transport.responseText;
                    // update
                    $$('.col-main').each(
                        function (e) {
                            e.update(response);
                        }
                    );
                },
                onFailure: function(){
                    alert('<?php echo $this->jsQuoteEscape($this->__('Server Error. Please try again.')) ?>');
                }
            });

        }
    </script>
</div>
<?php endif; ?>