<?php
$checkoutHelper = Mage::helper('onestepcheckout/checkout');
$current_code = Mage::app()->getStore()->getCurrentCurrency()->getCode();
$payment = $this->getQuote()->getPayment()->getMethod();
?>
<table class="onestepcheckout-summary">
    <thead>
        <tr>
            <th class="name"><?php echo $this->__('Product'); ?></th>
            <th class="qty"><?php echo $this->__('Qty'); ?></th>
            <th class="total"><?php echo $this->__('Subtotal'); ?></th>
            <?php if($current_code!='USD'&&$payment=='paypal_express'): ?>
            <th class="total"><?php echo $this->__('Subtotal').'(USD)'; ?></th>
            <?php endif; ?>
        </tr>
    </thead>
    <?php foreach($this->getItems() as $item): ?>
    <tr>
        <td class="name">
            <?php echo $item->getName(); ?>
            <?php if($checkoutHelper->settings['show_custom_options']): ?>
                <?php $options = $item->getProduct()->getTypeInstance(true)->getOrderOptions($item->getProduct()); ?>
                <?php if(isset($options['options']) && count($options['options']) > 0): ?>
                <ul class="onestepcheckout-custom-options">
                <?php foreach($options['options'] as $option): ?>
                    <li><b><?php echo $option['label'] . ':</b> ' . $option['value']; ?></li>
                <?php endforeach; ?>
                </ul>
                <?php endif; ?>

                <?php if($item->getProduct()->isConfigurable()): ?>

                <?php
                $configurable_options = $item->getProduct()->getTypeInstance(true)->getSelectedAttributesInfo($item->getProduct());
                ?>

                <?php if(is_array($configurable_options) && count($configurable_options) > 0): ?>
                <ul class="onestepcheckout-custom-options">
                <?php foreach($configurable_options as $option): ?>
                    <li><b><?php echo $option['label']; ?>:</b> <?php echo $option['value']; ?></li>
                <?php endforeach; ?>
                </ul>
                <?php endif; ?>

                <?php endif; ?>

            <?php endif; ?>
        </td>
        <td class="qty"><?php echo $item->getQty(); ?></td>
        <td class="total">
            <?php if($checkoutHelper->settings['display_tax_included']): ?>
            <?php echo $this->helper('checkout')->formatPrice($this->helper('checkout')->getSubtotalInclTax($item)); ?>
            <?php else: ?>
            <?php echo $this->helper('checkout')->formatPrice($item->getRowTotal()); ?>
            <?php endif; ?>
        </td>
        <?php if($current_code!='USD'&&$payment=='paypal_express'): ?>
        <td class="total"><?php echo '($'.number_format($item->getBaseRowTotal(),2).')'; ?></td>
        <?php endif; ?>
    </tr>
    <?php endforeach; ?>
</table>

<table class="onestepcheckout-totals">
    <?php foreach($this->getTotals() as $total): ?>
    <tr<?php if($total->getCode() == 'grand_total'): ?> class="grand-total"<?php endif; ?>>
        <td class="title">

            <?php

            $code = $total->getCode();
            $value = $total->getValue();

            if($code == 'subtotal')    {
                $total_name = $this->__('Subtotal');
                $base_value = $this->getQuote()->getShippingAddress()->getBaseSubtotal();
            }
            elseif($code == 'shipping')    {
                $total_name = $this->__('Shipping');
                if($checkoutHelper->settings['display_tax_included'])   {
                    $value += $this->getQuote()->getShippingAddress()->getShippingTaxAmount();
                }
                $base_value = $this->getQuote()->getShippingAddress()->getBaseShippingAmount();
            }
            elseif($code == 'grand_total')    {
                $total_name = $this->__('Grand total');
                $base_value = $this->getQuote()->getBaseGrandTotal();
            }
            else    {
                $total_name = $total->getTitle();
            }

            echo $total_name;

            ?>
        </td>
        <td class="value">
            <?php echo $this->helper('checkout')->formatPrice($value); ?>
        </td>
        <?php if($current_code!='USD'&&$payment=='paypal_express'): ?>
        <td class="value">
            <?php echo '($'.number_format($base_value,2).')'; ?>
        </td>
        <?php endif; ?>
    </tr>
    <?php endforeach; ?>
</table>
