<?php
/**
 * Adyen Payment Module
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category    Adyen
 * @package    Adyen_Payment
 * @copyright    Copyright (c) 2011 Adyen (http://www.adyen.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
/**
 * @category   Payment Gateway
 * @package    Adyen_Payment
 * @author     Adyen
 * @property   Adyen B.V
 * @copyright  Copyright (c) 2014 Adyen BV (http://www.adyen.com)
 */
?>
<?php echo $this->htmlEscape($this->getMethod()->getTitle()) ?><br/>
<?php if ($_info = $this->getInfo()): ?>
    <?php if ($_info->getAdyenPspReference() == ''): ?>
        <?php echo Mage::helper('adyen')->__('Payment has not been processed yet.') ?> <br/>
    <?php else : ?>
        <?php if ($this->getMethod()->getConfigDataDemoMode()): ?>
            <?php echo Mage::helper('adyen')->__('Adyen PSP Reference: <a href="https://ca-test.adyen.com/ca/ca/accounts/showTx.shtml?pspReference=%s&txType=Payment" target="__blank">%s</a>', $this->htmlEscape($_info->getAdyenPspReference()), $this->htmlEscape($_info->getAdyenPspReference())) ?>
            <br/>
        <?php else : ?>
            <?php echo Mage::helper('adyen')->__('Adyen PSP Reference: <a href="https://ca-live.adyen.com/ca/ca/accounts/showTx.shtml?pspReference=%s&txType=Payment" target="__blank">%s</a>', $this->htmlEscape($_info->getAdyenPspReference()), $this->htmlEscape($_info->getAdyenPspReference())) ?>
            <br/>
        <?php endif; ?>
    <?php endif; ?>
    <?php $paymentMethod = $_info->getCcType() ?>
    <?php if (!empty($paymentMethod)): ?>
        <?php echo $this->__('Payment Method: %s', $this->htmlEscape($paymentMethod)) ?><br/>
    <?php endif; ?>
    <?php if ($_info->getAdditionalInformation("hpp_issuer_id") !== null): ?>
        <?php $bankData = $_info->getAdditionalInformation("hpp_issuer_id"); ?>
        <?php if (!empty($bankData)) : ?>
            <?php
            // for older versions < 2.5.2
            $id = explode(DS, $bankData);
            $label = isset($id['1']) ? $id['1'] : "";

            // older versions > 2.5.2
            if ($label == "") {
                $label = $_info->getAdditionalInformation('hpp_type_bank_label');
            }

            ?>
            <?php echo $this->__('Bank: %s', $this->htmlEscape($label)) ?><br/>
        <?php endif; ?>
    <?php endif; ?>
    <?php if ($this->htmlEscape($this->getInfo()->getAdyenTotalFraudScore()) != ""): ?>
        <?php echo Mage::helper('adyen')->__('Total fraud score: %s', $this->htmlEscape($this->getInfo()->getAdyenTotalFraudScore())) ?>
        <br/>
    <?php endif; ?>
    <?php if ($_info->getAdyenKlarnaNumber() != null && $_info->getAdyenKlarnaNumber() != ""): ?>
        <?php echo Mage::helper('adyen')->__('Klarna reservation number: %s', $this->htmlEscape($_info->getAdyenKlarnaNumber())) ?>
        <br/>
    <?php endif; ?>
    <?php if ($this->htmlEscape($this->getInfo()->getAdyenRefusalReasonRaw()) != ""): ?>
        <?php echo Mage::helper('adyen')->__('Raw acquirer response: %s', $this->htmlEscape($this->getInfo()->getAdyenRefusalReasonRaw())) ?>
        <br/>
    <?php endif; ?>
    <?php if ($this->htmlEscape($this->getInfo()->getAdyenAuthCode()) != ""): ?>
        <?php echo Mage::helper('adyen')->__('Authorisation code: %s', $this->htmlEscape($this->getInfo()->getAdyenAuthCode())) ?>
        <br/>
    <?php endif; ?>
    <?php if ($this->htmlEscape($this->getInfo()->getAdyenAcquirerReference()) != ""): ?>
        <?php echo Mage::helper('adyen')->__('Acquirer reference: %s', $this->htmlEscape($this->getInfo()->getAdyenAcquirerReference())) ?>
        <br/>
    <?php endif; ?>

    <!--    show split paymetn-->

    <?php if ($this->getSplitPayments()): ?>
        <table>
            <tr>
                <th>PspReference</th>
                <th>Payment Method</th>
                <th>Amount</th>
                <th>Refunded</th>
            </tr>
            <?php foreach ($this->getSplitPayments() as $payment): ?>
                <tr>
                    <td><?php echo $payment->getPspreference() ?></td>
                    <td><?php echo $payment->getPaymentMethod() ?></td>
                    <td><?php echo $payment->getAmount() ?></td>
                    <td><?php echo $payment->getTotalRefunded() ?></td>
                </tr>
            <?php endforeach; ?>
        </table>
    <?php endif; ?>

<?php endif; ?>
